dist: jammy
language: node_js
node_js:
  - 20
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
  - rm -rf src test tsconfig.test.json jest.config.js .prettierrc .nvmrc .gitignore
    node_modules .travis.yml make-executable.js tsconfig.json
deploy:
  provider: npm
  email: kristian.zuffa@gmail.com
  skip_cleanup: true
  api_key:
    secure: CaXY5qWB0SeUlBKSvn2TZ7maebvuY9khny37xl6TKCnLhrzGgZfqNs5+MHfn3jz5SLa15lpwiovl4p6fLWZKsxFzCuKqGVFoEWEt6mwzNVwQqjNORaxyn+TdeFliVre5PhGl6TFPmsEAkVgVsthcV3E/RR0C/+1BuarNP2tqtJTlL50J48ZCAzwfzeHC/jXicEmkNPd46TNnXkdBDsSuVNXm+rZ/po5FZWWEscKWqTPC+Bl2Tr4lvWuK2UaDqe0OQOO4BTweW4LDSnUaqPwHssp39XRDSqtDMT+qrGIQkskrhdf5yORN1MSwye/0WGbhEdVF7bX/33o2FxvIrX2HSmmuMdMECub/6RVjjF4V9Cpt9dUlWtborljfWIkeLKzWdyHL0cyzPu5ijjGMypkrln26WI069uz5gOHJ8kae69qUzlWDI4+ctvvNH4PbEZufqhr216D4iuLfDdh489WOPqiaWWZWul0gn4Yqd+GQXFxz4mE7kuDZOVBZy6KJYg7XoXnlQhDUyRYdAsMmghmxQe7Y1RffpA/X/9NVhTYgdAISMhc1LnnZ/8R60Yhx/h7qAsqtHZho7vz2aO10ekeI7xQG5SZq4p/HgHaCRbkQA7f9spDnSbYwnuWEzUxt2nvAHVV1vvoUAGSlJIbJJAwzt67V1Y+a6RriRrwBMaqHQNs=
  on:
    repo: zuffik/cucumber-generator
    branch: master

branches:
  only:
    - master
